import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/appSidebar";
import "./globals.css";
import { GameProvider } from "@/components/game/gameContextProvider";
import TopBar from "@/components/topBar";
import { Toaster } from "sonner";
import { MathJaxContext } from "better-react-mathjax";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <MathJaxContext>
          <GameProvider>
            <SidebarProvider>
              <AppSidebar />
              <main className="w-screen h-screen">
                <TopBar />
                {children}
              </main>
              <Toaster />
            </SidebarProvider>
          </GameProvider>
        </MathJaxContext>
      </body>
    </html>
  );
}
